### ISSUE TITLE
Navigation and Accessibility

### ISSUE THREAD

**Issue by Zalakshah786** [Zalakshah786/hackathon-project1#1]
As a user seeking inner peace and harmony, I want to access a website that provides information about the benefits of meditation and yoga, so that I can learn basic poses and techniques to get started

**Comment by Zalakshah786** [comment]
**User Story:**

- As a user seeking inner peace and harmony, I want to access a website that provides information about the benefits of meditation and yoga, so that I can learn basic poses and techniques to get started.

**Acceptance Criteria:**

- [x] The website should have a welcoming home page with an introduction to the benefits of meditation and yoga.

- [x] The home page should feature a carousel section with images and captions promoting tranquillity and mindfulness.

- [x] Navigation should be easy with accessible links to "Home," "benefits," "Services," and "contact us" pages.

- [x] The website should be responsive and viewable on both desktop and mobile devices.
 
**Tasks**

Homepage Design: Create and style the homepage with HTML and CSS.
Carousel Section: Implement and style the carousel with images and captions.
Navigation Menu: Develop a responsive navigation menu linking to "Home," "About," "Services," and "Sign Up" pages.
Responsive Design: Ensure the website is responsive for both desktop and mobile device.

**Comment by Zalakshah786** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="Learn about the benefits of meditation and yoga, and discover basic poses and techniques to get started.">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
  <title>Serenity</title>

  
  <link rel="stylesheet" href="/assest/css/style.css">
</head>

<body>
  
  <header>
    <a href="index.html">
      <h1>Welcome to Serenity
        <p> Discover Inner peace and Harmony </p>
      </h1>
    </a>
    <input type="checkbox" id="nav-toggle" name="nav-toggle">
    <label for="nav-toggle" class="nav-toggle-label">
      <i class="fa-solid fa-bars"></i>
    </label>
    <nav>
      <ul id="menu">
        <li><a href="index.html" aria-current="page" class="active">Home</a></li>
        <li><a href="benefits.html"  aria-current="page" class="active">Benefits</a></li>
        <li><a href="services.html" aria-current="page" class="active">Services</a></li>
        <li><a href="contact.html" aria-current="page" class="active">Contact Us</a></li>
      </ul>
    </nav>
  </header>

  
  <main>
    
    <section id="blurred-background">
      <div id="heroCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="/assest/images/heroimage.webp.jpg"class="d-block w-100"alt="Serenity landscape, symbolizing peace and calm">
            <div class="carousel-caption d-none d-md-block">
              <h1>Welcome to Serenity</h1>
              <p>Discover Inner Peace and Harmony</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="/assest/images/image1 carasoul.webp.jpg"class="d-block w-100"alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
              <h1>Embrace Tranquility</h1>
              <p>welcome a state of peace and calmness.appreciate moments of quiet and relaxation in their lives.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="/assest/images/carsoul image 3.webp.jpg"class="d-block w-100"alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
              <h1>Mindful Meditation</h1>
              <p>Achieve Inner Calm</p>
            </div>
          </div>

        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#heroCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#heroCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

      </div>

      
      <section id="benefits" class="container section">
        <div class="row">
          <div class="col-12 text-center">
            <h2 class="display-6">Benefits of Yoga and Meditation</h2>
          </div>
          <div class="col-12 col-md-6 col-xl-2">
            <div class="card">
              <img src="/assest/images/yoga posture.webp.jpg"class="card-img-top"alt="Improved Flexibility">
              <div class="card-body">
                <h3 class="card-title">Improved Flexibility</h3>
                <p class="card-text">Yoga poses enhance flexibility and improve physical health.</p>
                </p>
              </div>
            </div>
          </div>

          <div class="col-12 col-md-6 col-xl-2">
            <div class="card">
              <img src="/assest/images/benefits image 2.webp.webp"class="card-img-top">
              <div class="card-body">
                <h3 class="card-title">Stress Relief</h3>
                <p class="card-text">Meditation and yoga help reduce stress and promote relaxation.</p>
              </div>

            </div>
          </div>
          <div class="col-12 col-md-6 col-xl-2">
            <div class="card">
              <img src="/assest/images/benefits image 2.webp.webp"class="card-img-top">
              <div class="card-body">
                <h3 class="card-title">Embrace Tranquility</h3>
                <p class="card-text">welcome a state of peace and calmness.appreciate moments of quiet and relaxation in
                  their lives.</p>
              </div>

            </div>
          </div>
          <div class="col-12 col-md-6 col-xl-2">
            <div class="card">
              <img src="/assest/images/benefits image 4.webp.webp"class="card-img-top">
              <div class="card-body">
                <h3 class="card-title">Workshops</h3>
                <p class="card-text">Attend our workshops to learn more about meditation and yoga techniques.</p>
              </div>

            </div>
          </div>

      </section>

      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+3o5n5hb7ie1e5z0I5i5Vt+0I5i5V"
        crossorigin="anonymous"></script>
</body>

</div>
</section>
</main>

  
  
  <footer id="contact" class="mt-auto">
    <div class="container section">
      <div class="row justify-content-center">
        <div class="col-12 text-center">
          <h2 class="display-6">Contact us!</h2>
        </div>
        
        <div class="col-12 col-md-6 col-xl-4">
          <h3>Contact info</h3>
          <address>
            <strong><i class="fa-solid fa-location-dot"></i> Serenity House</strong><br>
            123 Serenity House<br>
            Maidenhead 12345<br>
          </address>
          <p><i class="fa-solid fa-phone"></i> 012 345 6789<br>
            <i class="fa-regular fa-paper-plane"></i> info@Serenity.co
          </p>
          <div class="social-links my-4">
            <a href="https://www.instagram.com" target="_blank"
              aria-label="Visit our Instagram page (opens in a new tab)" rel="noopener"><i
                class="fa-brands fa-instagram"></i></a>
            <a href="https://www.facebook.com" target="_blank" aria-label="Visit our Facebook page (opens in a new tab)"
              rel="noopener"><i class="fa-brands fa-square-facebook"></i></a>
            <a href="https://www.x.com" target="_blank" aria-label="Visit our X feed (opens in a new tab)"
              rel="noopener"><i class="fa-brands fa-x-twitter"></i></a>
          </div>
        </div>
  </footer>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>

  
  <script src="https://kit.fontawesome.com/8669b8ad66.js" crossorigin="anonymous"></script>
  
  </script>
  </body>

</html>
